---
title: "Data-dr-wisnu"
author: "Kadek Adit Wiryadana"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Library
```{r library}
library(googlesheets4)
library(tidyverse)
library(patchwork)
library(gt)
library(gtsummary)
library(flextable)
library(ggdist)
library(ggVennDiagram)
```

## Import Data
### google authentication
```{r auth, eval=FALSE}
googlesheets4::gs4_auth()
```

### Import Data from googlesheet
```{r import_data, eval=FALSE}
data <- read_sheet("https://docs.google.com/spreadsheets/d/1QgE55fiI572kAgryc5ruExvcAz1GuuDk1dIhdD6wyxY/edit#gid=0")
write_csv(data, "data.csv")
```

### read data
```{r reread, warning=FALSE}
data <- read_csv("data.csv")
```
## Sneak Peak
```{r summary}
head(data) # 5 data awal
glimpse(data)
```
### Class variabel
```{r class_var, eval=FALSE}
#sapply(data, class)
```
### Recode Variabel
```{r recode}
# Rename variabel
colnames(data)[24] <- "Komorbid_HT" 
colnames(data)[25] <- "Komorbid_DM" 

# Recode jenis kelaim sebagai factor
data$Jenis.Kelamin <- factor(data$Jenis.Kelamin, levels=c("laki laki","perempuan"))

# Recode Gejala Utama sebagai factor
data$Gejala.Utama <-  factor(data$Gejala.Utama)
unique(data$Gejala.Utama)
# Ubah entri seragam
data$Gejala.Utama <- as.character(data$Gejala.Utama)
data$Gejala.Utama <-  ifelse(data$Gejala.Utama == "demam", "Demam", data$Gejala.Utama) #ubah demam jadi Demam
data$Gejala.Utama <-  ifelse(data$Gejala.Utama == "batuk", "Batuk", data$Gejala.Utama) #ubah batuk jadi Batuk
data$Gejala.Utama <-  factor(data$Gejala.Utama)
levels(data$Gejala.Utama)

# ubah kolum 9 (gejala tambahan batuk) hingga 22 (gejala tambahan anosmia), 24-33 jadi faktor
gej_tam_coloumn <- c(9:22, 24:33, 40, 42:44)
data[gej_tam_coloumn] <- lapply(data[gej_tam_coloumn], as.factor)
glimpse(data)
```
### Derajat Covid Diseragamkan
```{r}
summary(data$Derajat.Covid)

# berat ada versi, kritis ada 2 versi.
data$Derajat_new <- as.character(data$Derajat.Covid)
data$Derajat_new <- ifelse(data$Derajat_new == "Berat", "berat", data$Derajat_new) # Berat jadi berat
data$Derajat_new <- ifelse(data$Derajat_new == "berat(?)", "berat", data$Derajat_new) # berat(?) jadi berat

data$Derajat_new <- ifelse(grepl("kritis ", data$Derajat_new), "kritis", data$Derajat_new)
data$Derajat_new <- as.factor(data$Derajat_new)
summary(data$Derajat_new)
```



## Descriptive Analysis

### General Summary  
```{r general_summary}
summary(data[4:45])
```

### Demographics
```{r demog_table}
demog <- data %>% 
  select(Jenis.Kelamin,
         Umur) %>% 
  tbl_summary() %>% as_flex_table()

```

#### Data-vis Demographics
```{r}
age_dist <- ggplot(data = data, aes(x= Jenis.Kelamin, y=Umur, fill=Jenis.Kelamin)) +
  ggdist::stat_halfeye(adjust=0.5, width=0.6, .width=0, justification=-0.2, point_colour=NA) +
  geom_boxplot(width=0.12, alpha=0.5) +
  ggdist::stat_dots(side="left", justification=1.12, binwidth=1) +
  theme_minimal() +
  labs(
    title = " Distribusi Usia Berdasarkan Jenis Kelamin",
    y = "Usia (tahun)",
    x = "Jenis Kelamin",
    fill="Jenis Kelamin"
  ) +
coord_flip()

print(age_dist)




```



### Gejala
```{r}
gejala <- data %>%
  select(9:22) %>% 
  tbl_summary()

gejala
```

### Komorbid
```{r}
komorbid <- data %>%
  select(24:31) %>% 
  tbl_summary()

komorbid
```

```{r}
komorbid_list <- list(
 Hipertensi = select(filter(data, Komorbid_HT == "ya"), No),
 Diabetes = select(filter(data, Komorbid_DM == "ya"), No),
 'Tanpa Komorbid' = select(filter(data, Komorbid == "tidak"), No)
 )

komorbid_list <- lapply(komorbid_list, pull)

komorbid_venn <- ggVennDiagram(komorbid_list, show_intersect = F)

komorbid_venn

```



### Treatment & Control
```{r}
treat <- data %>%
  select(32,33) %>%
  tbl_summary()

treat
```
### Finding
```{r}
xray <- data %>%
  select(Xray) %>%
  tbl_summary()

xray
```

### Outcome
```{r}
outcome <- data %>%
  select(41:44) %>%
  tbl_summary()

outcome
```

### Outcome, age, DM & HT
```{r}
interaction <- ggplot(data = data, aes(x=Umur, y=Derajat_new, shape=Derajat_new,  colour=Komorbid_DM, fill=Komorbid_HT)) +
  geom_jitter(height=0.25) +
  scale_shape_manual(values=c(21,22,24))
  
interaction
```

```{r}
interaction2 <- ggplot(data = data, aes(x=Umur, y=Derajat_new)) +
  geom_jitter(height=0.15, aes(shape=Derajat_new,  colour=Komorbid_DM, fill=Komorbid_HT)) +
  #ggdist::stat_halfeye(justification=1.5, side="bottom", adjust=0.8, .width=0, width=0.5, height=0.3, point_colour=NA, aes(fill=Derajat_new)) +
  geom_boxplot(width=0.2, alpha=0.3, position = "dodge") +
  scale_shape_manual(values=c(21,22,24))
interaction2
```

